name: Daily Crypto Notify

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run notification script
        run: python main.py
