name: DexScreener Volume Spike Monitor

on:
  schedule:
    - cron: '*/15 * * * *'   # 每15分钟执行一次，实时监控
  workflow_dispatch:         # 允许手动触发

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache last volumes
        uses: actions/cache@v3
        with:
          path: last_volumes.json
          key: ${{ runner.os }}-last_volumes
          restore-keys: |
            ${{ runner.os }}-last_volumes

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run notification script
        env:
          WEBHOOK_NEWCOINS: ${{ secrets.WEBHOOK_NEWCOINS }}
        run: python main.py

      - name: Save cache
        uses: actions/cache@v3
        with:
          path: last_volumes.json
          key: ${{ runner.os }}-last_volumes
