name: Daily Crypto Notify

on:
  schedule:
    # 每天早上7点（北京时间）执行，UTC时间为前一天23点
    - cron: '0 23 * * *'

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run notification script
        run: python main.py
