name: Daily Crypto Notify

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 23 * * *'  # UTC时间23点执行（北京时间早上7点）

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run notification script
        env:
          WEBHOOK_NEWCOINS: ${{ secrets.WEBHOOK_NEWCOINS }}  # 传递Webhook给脚本
        run: python main.py
